### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Marcisbee**
# Description

This is example quote logic repo for [kasko/kasko-app-example](https://github.com/kasko/kasko-app-example).

# Checklist
- [x] I have tested this code locally
- [x] I have written unit tests
- [x] I looked over the submitted code and I am happy with the quality of it
- [ ] I have updated [the product documentation](https://github.com/kasko/docs)

_Please always fill in all the checkmarks. If some of them are not relevant, then please strikethrough them (~ symbol) and write a comment why it's not relevant._

### CODE REVIEW

**Review by tomstumshais — DISMISSED** [review]
Cool! 🌞

**Review by BerSteve — DISMISSED** [review]
Do we need to write quote specific tests in case of new pricing? If yes it's FE task?, right?

**Comment by Marcisbee** [comment]
> Do we need to write quote specific tests in case of new pricing? If yes it's FE task?, right?

Yes, we would still need to write some tests, but just a few to check that nothing breaks (like no errors happen and no weird output is sent back to `quote-svc`), but business logic tests would be written by PM's in dashboard. There will be an option to do that there.

**Review by mkasparsone — DISMISSED** [review]
Nice! 🎉

**Review by BerSteve — APPROVED** [review]

**Review by mkasparsone — APPROVED** [review]

**Review by tomstumshais — APPROVED** [review]

**Pull request merged**
