### PR TITLE
Excel only version

### PR DESCRIPTION
**Pull request by Marcisbee**
# Description

So I did split master branch into two:
1. [`master`](https://github.com/kasko/kasko-quote-example/tree/master) - excel only version;
2. [`parsed-xlsx`](https://github.com/kasko/kasko-quote-example/tree/parsed-xlsx) - parsed excel version;

Since PM's will start using this repo, will have to make everything as simple as possible, without any distractions.

In this PR I'm removing parse stuff from branch.

# Checklist
- [x] I have tested this code locally
- [ ] I have written unit tests
- [x] I looked over the submitted code and I am happy with the quality of it
- [ ] I have updated [the product documentation](https://github.com/kasko/docs)

_Please always fill in all the checkmarks. If some of them are not relevant, then please strikethrough them (~ symbol) and write a comment why it's not relevant._

### CODE REVIEW

**Comment by tomstumshais** [comment]
Parse excel mode is only for devs?

**Comment by Marcisbee** [comment]
@tomstumshais Yes, only for devs and only when targeting `js-pricing` not `xlsx-pricing` because output of parsed version is just one `js` file.

**Review by tomstumshais — DISMISSED** [review]

**Comment by tomstumshais** [comment]
Just an idea: can we add some note in README, that there is this advanced mode too?

**Comment by Marcisbee** [comment]
@tomstumshais updated readme

**Review by tomstumshais — APPROVED** [review]
Sweet! 🚀

**Pull request merged**
